services:
  traefik:
    image: "traefik:v3.3"
    container_name: traefik_container
    restart: unless-stopped
    command:
      - "--api.insecure=true" # Enable insecure API access
      - "--providers.docker=true" # Enable Docker provider
      - "--entrypoints.web.address=:80" # Define entrypoint for HTTP
      - "--entrypoints.websecure.address=:443" # Define entrypoint for HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure" # Redirect HTTP to HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https" # Use HTTPS scheme for redirection
      - "--certificatesresolvers.myresolver.acme.email=mojoyodajojo@gmail.com" # Email for ACME certificate resolver
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Storage location for ACME certificates
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Enable TLS challenge for ACME
      - "accesslog=true" # Enable access logs
      - "log-level=DEBUG" # Set log level to DEBUG
      - "--certi" # Incomplete command, should be removed or completed
    expose:
      - "8080"
    ports:
      - "80:80" # Map port 80 for HTTP
      - "443:443" # Map port 443 for HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Mount Docker socket
      - "./letsencrypt:/letsencrypt" # Mount directory for Let's Encrypt certificates
    
  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile
    container_name: auth-api_container
    ports:
      - "8081:8081"
    environment:
      - AUTH_API_PORT=8081
      - JWT_SECRET=${JWT_SECRET}
      - USERS_API_ADDRESS=http://users-api:8083
    depends_on:
      - traefik
    labels:
      - "traefik_enabled=true"
      - "traefik.http.routers.authapi.rule=Host(`auth.2doapp-hng.cloud`)"
      - "traefik.http.services.myservice.loadbalancer.server.port=80"
      - "traefik.http.routers.authapi-http.entrypoints=web"
      - "traefik.http.routers.authapi-http.rule=Host(`auth.2doapp-hng.cloud`)"
      - "traefik.http.routers.authapi-http.middlewares=redirect-to-https"
      - "traefik.http.routers.authapi-https.entrypoints=websecure"
      - "traefik.http.routers.authapi-https.rule=Host(`auth.2doapp-hng.cloud`)"
      - "traefik.http.routers.authapi-https.tls=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    depends_on:
      - auth-api
      - todos-api
      #- traefik
    labels:
      - "traefik_enabled=true"
      - "traefik.http.routers.frontend.rule=Host(`2doapp-hng.cloud`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.frontend-http.service=frontend"
      - "traefik.http.routers.frontend-http.rule=Host(`2doapp-hng.cloud`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-to-https"
      - "traefik.http.routers.frontend-https.service=frontend"
      - "traefik.http.routers.frontend-https.rule=Host(`2doapp-hng.cloud`)"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile
    container_name: log_message_processor_container
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=log_channel
    depends_on:
      - traefik  

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile
    container_name: todos-api_container
    ports:
      - "${REDIS_PORT}:8082"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    depends_on:
      - traefik
    labels:
      - "traefik_enabled=true"
      - "traefik.http.routers.todosapi.rule=Host(`todos.2doapp-hng.cloud`)"
      - "traefik.http.routers.todosapi-http.entrypoints=web"
      - "traefik.http.routers.todosapi-http.rule=Host(`todos.2doapp-hng.cloud`)"
      - "traefik.http.routers.todosapi-https.tls.certresolver=myresolver"
      - "traefik.http.routers.todosapi-http.middlewares=redirect-to-https"
      - "traefik.http.routers.todosapi-https.entrypoints=websecure"
      - "traefik.http.routers.todosapi-https.rule=Host(`todos.2doapp-hng.cloud`)"
      - "traefik.http.routers.todosapi-https.tls=true"
      - "traefik.http.routers.todosapi-http.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
    
  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile
    container_name: users-api_container
    ports:
      - "${SERVER_PORT}:8083"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - traefik
    labels:
      - "traefik_enabled=true"
      - "traefik.http.routers.users-api.rule=Host(`users.2doapp-hng.cloud`)"
      - "traefik.http.routers.users-api-http.entrypoints=web"
      - "traefik.http.routers.users-api-http.rule=Host(`users.2doapp-hng.cloud`)"
      - "traefik.http.routers.users-api-https.tls.certresolver=myresolver"
      - "traefik.http.routers.users-api-http.middlewares=redirect-to-https"
      - "traefik.http.routers.users-api-https.entrypoints=websecure"
      - "traefik.http.routers.users-api-https.rule=Host(`users.2doapp-hng.cloud`)"
      - "traefik.http.routers.users-api-https.tls=true"
      - "traefik.http.routers.users-api-http.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.scheme=https"
      - "traefik.http.middlewares.redirect-https.redirectScheme.permanent=true"
